## Common to all Computo publications
number-sections: true
format:
  html:
    include-in-header:
      - includes/metrics.html
      - includes/pseudocode-header.html
    include-before-body: includes/banner.html
    include-after-body: includes/pseudocode-footer.html
    toc-title: Contents
    toc: true
    theme: cosmo
    hover-citations: true
    hover-footnotes: true
    highlight-style: github
    code-background: true
    code-border-left: "#31BAE9"
    code-tools:
      source: true
      toggle: false
      caption: "source"
    code-copy: true
    code-fold: true
    code-summary: "Show the code"
    anchor-sections: true
    link-external-icon: false
    link-external-newwindow: true
    html-math-method: katex
    self-contained: true
crossref:
  sec-prefix: Section
  eq-prefix: Equation
  fig-prefix: Figure   
  tbl-prefix: Table
execute:
  keep-ipynb: true
