name: build

on:
  schedule:
    - cron: '0 0 * * 0' 
  push:
    branches:
      - master
      - main

env: # Change this if needed
  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-deploy:
    if: "!contains(github.event.head_commit.message, 'skip build')"
    runs-on: ubuntu-latest

    steps:
      - name: Checking out repository for Github action
        uses: actions/checkout@v3

      - name: Cache conda
        uses: actions/cache@v1
        env:
          # Increase this value to reset cache if environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.yml') }}

      - name: Installing dependencies with Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: false
          miniconda-version: 'latest'
          python-version: 3.9
          environment-file: environment.yml
          activate-environment: computo

      - name: Set up Quarto and install Computo extension
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          # To manage extension
          version: pre-release
        run: |
            quarto install --no-prompt extension computorg/computo-quarto-extension
     
      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions

