name: build

on:
  push:
    branches:
      - main

jobs:
  computorticle:
    runs-on: "ubuntu-latest"

    steps:
      - name: Checking out repository for Github action
        uses: actions/checkout@v2

      - name: Installing dependencies with Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: false
          miniconda-version: 'latest'
          python-version: 3.9
          environment-file: environment.yml
          activate-environment: computo

      - name: "Install Quarto and render"
        uses: pommevilla/quarto-render@main
      
#      - name: Download last version of quarto
#        uses: wei/wget@v1
#        with:
#          args: -O quarto.deb https://github.com/quarto-dev/quarto-cli/releases/latest/download/quarto-0.2.94-amd64.deb
        
#      - name: Install Quarto
#        shell: bash -l {0} 
#        run: |
            sudo dpkg -i quarto.deb

#      - name: Rendering with Quarto
#        shell: bash -l {0}
#        run: |
#            mkdir _build
#            quarto render content.qmd
#            mv content.html _build/index.html

      - name: Deploying article on github pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: ./_site
          CLEAN: true
